### PR TITLE
added two assertions for num classes must be bigger than 1

### PR DESCRIPTION
**Pull request by tomerkeren42**
When trying to use IoU or Dice with num of classes == 1, things will collapse and a lot of bleeding can happen - unless you use the dedicated Binary equivalence. 
One (me) might not know the equivalence exist and sweat out trying to use the general ones.

### CODE REVIEW

**Review by NatanBagrov — DISMISSED** [review]
LGTM, should save time :)

**Review by shaydeci — CHANGES_REQUESTED** [review]
Don't use asserts, raise informative errors instead.

**Comment by tomerkeren42** [comment]
> 

d1d91212

**Review by shaydeci — APPROVED** [review]
LGTM

**Review by shaydeci — APPROVED** [review]

**Pull request merged**
