### PR TITLE
Feature/sg 691 register dynamically metrics and datasets

### PR DESCRIPTION
**Pull request by Louis-Dupont**

### CODE REVIEW

**Comment by BloodAxe** [comment]
For sake of plaing safe, let's run integration tests suites on this PR to ensure we can train our recipes and nothing gets broken. After file conflicts are resolved we can merge it

**Review by BloodAxe — DISMISSED** [review]
LGTM if it pass integration tests

**Review by ofrimasad — APPROVED** [review]
LGTM

**Review by shaydeci — APPROVED** [review]
LGTM

**Pull request merged**
