### PR TITLE
Add documentation for DatasetAdapter

### PR DESCRIPTION
**Pull request by Louis-Dupont**
PR for Dataloader Adapter documentation. 

The .md is generated from the notebook.

The notebook cannot be run automatically in tests because it requires user inputs.

### CODE REVIEW

**Comment by BloodAxe** [comment]
Pls update install instructions FROM

```
!pip install data-gradients==0.2.1 gwpy &> /dev/null
!pip install super-gradients==3.3.1 gwpy &> /dev/null
!pip freeze gwpy &> /dev/null

```
TO 

`!pip install -qq super-gradients==3.3.1`

**Comment by BloodAxe** [comment]
This https://github.com/Deci-AI/super-gradients/pull/1607 should be merged before current PR

**Comment by Louis-Dupont** [comment]
`pip install ...` changed in [ff78e13](https://github.com/Deci-AI/super-gradients/pull/1591/commits/ff78e13b91caf3c85dd1dc7d2f0d4b11fd7a0ae4)

**Comment by BloodAxe** [comment]
Please update the installed version of SG to latest 3.4.1:

`!pip install -q super-gradients==3.3.1`

**Review by BloodAxe — APPROVED** [review]
LGTM

**Pull request merged**
